// <auto-generated />
using System;
using LingEdu.Exercises.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LingEdu.Exercises.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ExercisesDbContext))]
    [Migration("20251220135254_InitialExercises")]
    partial class InitialExercises
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LingEdu.Exercises.Domain.Exercises.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("bit");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Exercises", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            IsPremium = false,
                            Level = 1,
                            Title = "Present Simple Basics",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            IsPremium = true,
                            Level = 2,
                            Title = "Past Simple Challenge",
                            Type = 1
                        });
                });

            modelBuilder.Entity("LingEdu.Exercises.Domain.Exercises.QuizOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuizOptions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1111111-1111-1111-1111-111111111111"),
                            IsCorrect = true,
                            QuestionId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1"),
                            Text = "goes"
                        },
                        new
                        {
                            Id = new Guid("c1111111-1111-1111-1111-111111111112"),
                            IsCorrect = false,
                            QuestionId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1"),
                            Text = "go"
                        },
                        new
                        {
                            Id = new Guid("c1111111-1111-1111-1111-111111111113"),
                            IsCorrect = false,
                            QuestionId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1"),
                            Text = "going"
                        },
                        new
                        {
                            Id = new Guid("c1111111-1111-1111-1111-111111111114"),
                            IsCorrect = false,
                            QuestionId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1"),
                            Text = "gone"
                        },
                        new
                        {
                            Id = new Guid("c2222222-2222-2222-2222-222222222221"),
                            IsCorrect = true,
                            QuestionId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa2"),
                            Text = "drink"
                        },
                        new
                        {
                            Id = new Guid("c2222222-2222-2222-2222-222222222222"),
                            IsCorrect = false,
                            QuestionId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa2"),
                            Text = "drinks"
                        },
                        new
                        {
                            Id = new Guid("c2222222-2222-2222-2222-222222222223"),
                            IsCorrect = false,
                            QuestionId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa2"),
                            Text = "drank"
                        },
                        new
                        {
                            Id = new Guid("c2222222-2222-2222-2222-222222222224"),
                            IsCorrect = false,
                            QuestionId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa2"),
                            Text = "drinking"
                        },
                        new
                        {
                            Id = new Guid("d1111111-1111-1111-1111-111111111111"),
                            IsCorrect = true,
                            QuestionId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb1"),
                            Text = "watched"
                        },
                        new
                        {
                            Id = new Guid("d1111111-1111-1111-1111-111111111112"),
                            IsCorrect = false,
                            QuestionId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb1"),
                            Text = "watch"
                        },
                        new
                        {
                            Id = new Guid("d1111111-1111-1111-1111-111111111113"),
                            IsCorrect = false,
                            QuestionId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb1"),
                            Text = "watches"
                        },
                        new
                        {
                            Id = new Guid("d1111111-1111-1111-1111-111111111114"),
                            IsCorrect = false,
                            QuestionId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb1"),
                            Text = "watching"
                        },
                        new
                        {
                            Id = new Guid("d2222222-2222-2222-2222-222222222221"),
                            IsCorrect = true,
                            QuestionId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb2"),
                            Text = "went"
                        },
                        new
                        {
                            Id = new Guid("d2222222-2222-2222-2222-222222222222"),
                            IsCorrect = false,
                            QuestionId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb2"),
                            Text = "go"
                        },
                        new
                        {
                            Id = new Guid("d2222222-2222-2222-2222-222222222223"),
                            IsCorrect = false,
                            QuestionId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb2"),
                            Text = "goes"
                        },
                        new
                        {
                            Id = new Guid("d2222222-2222-2222-2222-222222222224"),
                            IsCorrect = false,
                            QuestionId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb2"),
                            Text = "going"
                        });
                });

            modelBuilder.Entity("LingEdu.Exercises.Domain.Exercises.QuizQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.ToTable("QuizQuestions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1"),
                            ExerciseId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Prompt = "Choose the correct form: She ___ to school every day."
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa2"),
                            ExerciseId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Prompt = "I ___ coffee in the morning."
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb1"),
                            ExerciseId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Prompt = "Choose the correct form: Yesterday, I ___ a movie."
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb2"),
                            ExerciseId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Prompt = "He ___ to work last Monday."
                        });
                });

            modelBuilder.Entity("LingEdu.Exercises.Domain.Progress.UserProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CompletedAt");

                    b.ToTable("UserProgress", (string)null);
                });

            modelBuilder.Entity("LingEdu.Exercises.Domain.Exercises.QuizOption", b =>
                {
                    b.HasOne("LingEdu.Exercises.Domain.Exercises.QuizQuestion", null)
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LingEdu.Exercises.Domain.Exercises.QuizQuestion", b =>
                {
                    b.HasOne("LingEdu.Exercises.Domain.Exercises.Exercise", null)
                        .WithMany("Questions")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LingEdu.Exercises.Domain.Exercises.Exercise", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("LingEdu.Exercises.Domain.Exercises.QuizQuestion", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
