<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
	  <TargetFramework>net10.0</TargetFramework>
	  <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="13.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.10" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Modules\Users\LingEdu.Users.Infrastructure\LingEdu.Users.Infrastructure.csproj" />
	  <ProjectReference Include="..\..\Contracts\LingEdu.Contracts\LingEdu.Contracts.csproj" />
	  <ProjectReference Include="..\..\Modules\Subscriptions\LingEdu.Subscriptions.Infrastructure\LingEdu.Subscriptions.Infrastructure.csproj" />
	  <ProjectReference Include="..\..\Modules\Exercises\LingEdu.Exercises.Infrastructure\LingEdu.Exercises.Infrastructure.csproj" />
	  <ProjectReference Include="..\..\Modules\Ranking\LingEdu.Ranking.Infrastructure\LingEdu.Ranking.Infrastructure.csproj" />
	  <ProjectReference Include="..\..\Modules\Contests\LingEdu.Contests.Infrastructure\LingEdu.Contests.Infrastructure.csproj" />
	  <ProjectReference Include="..\..\Modules\Reports\LingEdu.Reports.Infrastructure\LingEdu.Reports.Infrastructure.csproj" />
  </ItemGroup>

</Project>
